# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jruby-ehcache}
  s.version = "1.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Dylan Stamat}, %q{Jason Voegele}]
  s.date = %q{2012-03-14}
  s.description = %q{JRuby interface to the popular Java caching library Ehcache}
  s.email = [%q{dstamat@elctech.com}, %q{jvoegele@terracotta.org}]
  s.executables = [%q{ehcache}]
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "History.txt",
    "License.txt",
    "Manifest.txt",
    "PostInstall.txt",
    "README.txt",
    "Rakefile",
    "VERSION",
    "bin/ehcache",
    "config/ehcache.yml",
    "config/ehcache_manual_rmi.yml",
    "examples/ehcache.xml",
    "examples/jruby-ehcache.rb",
    "ext/ehcache-2.4.6/ehcache-core-2.4.6.jar",
    "ext/ehcache-2.4.6/ehcache-terracotta-2.4.6.jar",
    "ext/ehcache-2.4.6/slf4j-api-1.6.1.jar",
    "ext/ehcache-2.4.6/slf4j-jdk14-1.6.1.jar",
    "ext/ehcache-2.4.6/terracotta-toolkit-1.3-runtime-3.3.0.jar",
    "jruby-ehcache-rails2.gemspec",
    "jruby-ehcache-rails3.gemspec",
    "jruby-ehcache.gemspec",
    "lib/ehcache.rb",
    "lib/ehcache/cache.rb",
    "lib/ehcache/cache_manager.rb",
    "lib/ehcache/config.rb",
    "lib/ehcache/element.rb",
    "lib/ehcache/extensions.rb",
    "lib/ehcache/java.rb",
    "lib/ehcache/yaml_config.rb",
    "script/console",
    "script/destroy",
    "script/generate",
    "script/txt2html",
    "spec/cache_manager_spec.rb",
    "spec/cache_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "tasks/deployment.rake",
    "tasks/environment.rake",
    "tasks/website.rake",
    "test/ehcache.xml",
    "test/ehcache.yml",
    "test/test_cache.rb",
    "test/test_cache_manager.rb",
    "test/test_configuration.rb",
    "test/test_ehcache.rb",
    "test/test_element.rb",
    "test/test_helper.rb",
    "test/test_yaml_config.rb",
    "website/index.html",
    "website/javascripts/rounded_corners_lite.inc.js",
    "website/stylesheets/screen.css",
    "website/template.html.erb"
  ]
  s.homepage = %q{http://ehcache.rubyforge.org}
  s.require_paths = [%q{lib}]
  s.rubyforge_project = %q{ehcache}
  s.rubygems_version = %q{1.8.9}
  s.summary = %q{JRuby interface to Ehcache}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.1') then
      s.add_runtime_dependency(%q<jruby-ehcache>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<jruby-ehcache>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<jruby-ehcache>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

